server:
  port: 8080
# Spring config
spring:
  application:
    name: libraryManagementSystem
  profiles:
    active: dev #change profile for every deployment. values are dev, stage or production

    main:
      web-environment: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

flyway.baseline-on-migrate: true