# Spring config
spring:
  flyway:
    enabled: true
    schemas: libraryManagementSystem
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/libraryManagementSystem
    username: root
    password: root
    initialization-mode: always
